spring.application.name=controle-fluxo

# Ativa o perfil 'local' (o Spring vai carregar o application-local.properties)
spring.profiles.active=local

# Configurações gerais do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true